runtime: go114
env: standard
main: ./cmd/attend-io-server

handlers:
  - url: /docs
    static_dir: /docs
    http_headers:
      Access-Control-Allow-Origin: http://attend-io-294107.uc.r.appspot.com
