runtime: go114
env: standard
main: ./cmd/attend-io-server

handlers:
- url: /docs
  static_dir: ./docs
  http_headers:
    Access-Control-Allow-Origin: '*'

env_variables:
  GCLOUD_DATASET_ID: attend-io-294107

