---
x-google-allow: all
swagger: "2.0"
info:
  description: A simple talk attendance API
  title: attend.io
  version: 1.0.0
consumes:
  - application/github.com/sctskw/attend.io.v1+json
produces:
  - application/github.com/sctskw/attend.io.v1+json
schemes:
  - http
paths:
  /:
    get:
      tags:
        - system
      responses:
        200:
          description: api status
          schema:
            type: object
            $ref: "#/definitions/SystemStatus"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /talks:
    get:
      tags:
        - talks
      responses:
        200:
          description: list the talks
          schema:
            $ref: "#/definitions/TalkList"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /talks/{id}:
    get:
      tags:
        - talks
      operationId: getTalkById
      parameters:
        - name: id
          in: path
          description: Talk ID
          type: string
          required: true
      responses:
        200:
          description: the requested talk
          schema:
            $ref: "#/definitions/Talk"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"


  /talks/{id}/attendees:
    get:
      tags:
        - talks
      operationId: getTalkAttendees
      parameters:
        - name: id
          in: path
          description: Talk ID
          type: string
          required: true
      responses:
        200:
          description: the list of attendees from the event
          schema:
            $ref: "#/definitions/AttendeesList"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /attendees:
    get:
      tags:
        - attendees
      operationId: getAttendeeByField
      parameters:
        - name: email
          in: query
          description: Attendee Email
          type: string
          format: email
        - name: id
          in: query
          description: Attendee ID
          type: string
      responses:
        200:
          description: find an attendee by id
          schema:
            $ref: "#/definitions/Attendee"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"


definitions:

  Talk:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
        minLength: 1
      presenter:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      date_time_start:
        type: string
        format: date-time
      date_time_end:
        type: string
        format: date-time
      ref_talk:
        $ref: "#/definitions/Talk"
      ref_attendees:
        $ref: "#/definitions/AttendeesList"

  TalkList:
    type: array
    items:
      $ref: "#/definitions/Talk"

  Attendee:
    type: object
    required:
      - name_first
      - name_last
    properties:
      id:
        type: string
        readOnly: true
      name_display:
        type: string
        minLength: 1
      name_first:
        type: string
        minLength: 1
      name_last:
        type: string
        minLength: 1
      email:
        type: string
        format: email

  AttendeesList:
    type: array
    items:
      $ref: "#/definitions/Attendee"

  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

  SystemStatus:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
