---
swagger: "2.0"
info:
  description: A simple talk attendance API
  title: attend.io
  version: 1.0.0
consumes:
- application/github.com/sctskw/attend.io.v1+json
produces:
  - application/github.com/sctskw/attend.io.v1+json
schemes:
  - http
paths:
  /:
    get:
      tags:
        - system
      responses:
        200:
          description: api status
          schema:
            type: object
            $ref: "#/definitions/SystemStatus"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /talks:
    get:
      tags:
        - talks
      responses:
        200:
          description: list the talks
          schema:
            type: array
            items:
              $ref: "#/definitions/Talk"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

definitions:
  Talk:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      name:
        type: string
        minLength: 1

      attendees:
        $ref: "#/definitions/AttendeesList"

  Attendee:
    type: object
    required:
      - name_first
      - name_last
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      name_display:
        type: string
        minLength: 1
      name_first:
        type: string
        minLength: 1
      name_last:
        type: string
        minLength: 1
      email:
        type: string
        format: email

  AttendeesList:
    type: array
    items:
      $ref: "#/definitions/Attendee"

  Event:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      name:
        type: string
        minLength: 1
      talk:
        type: string
        format: uuid

  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

  SystemStatus:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
