---
swagger: "2.0"
info:
  description: A simple talk attendance API
  title: attend.io
  version: 1.0.0
consumes:
- application/github.com/sctskw/attend.io.v1+json
produces:
  - application/github.com/sctskw/attend.io.v1+json
schemes:
  - http
paths:
  /:
    get:
      tags:
        - system
      responses:
        200:
          description: api status
          schema:
            type: object
            $ref: "#/definitions/SystemStatus"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /talks:
    get:
      tags:
        - talks
      responses:
        200:
          description: list the talks
          schema:
            type: array
            items:
              $ref: "#/definitions/Talk"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

definitions:
  Talk:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1

  Attendee:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: uuid
        readOnly: true
      name:
        type: string
        minLength: 1

  Event:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: uuid
        readOnly: true
      name:
        type: string
        minLength: 1
      talk:
        type: integer
        format: uuid

  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

  SystemStatus:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
