---
x-google-allow: all
swagger: "2.0"
info:
  description: A simple talk attendance API
  title: attend.io
  version: 0.0.1
consumes:
  - application/github.com/sctskw/attend.io.v1+json
produces:
  - application/github.com/sctskw/attend.io.v1+json
schemes:
  - http
paths:

  /talks:
    get:
      summary: Retrieve All Talks
      tags:
        - talks
      responses:
        200:
          description: list the talks
          schema:
            $ref: "#/definitions/TalkList"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

    post:
      summary: Create a Talk
      tags:
        - talks
      consumes:
        - application/json
      parameters:
        - in: body
          name: talk
          description: the Talk to create
          schema:
            $ref: "#/definitions/Talk"
      responses:
        200:
          description: Talk was created
          schema:
            $ref: "#/definitions/Talk"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /talks/{id}:
    get:
      summary: Retrieve a Talk by ID
      tags:
        - talks
      operationId: getTalkById
      parameters:
        - name: id
          in: path
          description: Talk ID
          type: string
          required: true
      responses:
        200:
          description: the requested talk
          schema:
            $ref: "#/definitions/Talk"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

    delete:
      summary: Deletes a Talk by ID
      operationId: deleteTalkById
      tags:
        - talks
      parameters:
        - name: id
          in: path
          description: Talk ID
          type: string
          required: true
      responses:
        204:
          description: Talk was deleted.
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /talks/{id}/attendees:
    get:
      summary: Retrieve the Attendees for a Talk
      tags:
        - talks
      operationId: getTalkAttendees
      parameters:
        - name: id
          in: path
          description: Talk ID
          type: string
          required: true
      responses:
        200:
          description: the list of attendees from the event
          schema:
            $ref: "#/definitions/AttendeeList"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

    patch:
      summary: Add an Attendee to a Talk
      tags:
        - talks
      operationId: addAttendeeToTalk
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: Talk ID
          type: string
          required: true
        - in: body
          name: attendees
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: Attendee was Added
          schema:
            $ref: "#/definitions/Talk"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"


  /talks/{id}/attendees/{attendeeId}:
    delete:
      summary: Remove an Attendee from a Talk
      tags:
        - talks
      operationId: deleteAttendeeFromTalk
      parameters:
        - name: id
          in: path
          description: Talk ID
          type: string
          required: true
        - name: attendeeId
          in: path
          description: Attendee ID
          type: string
          required: true
      responses:
        204:
          description: Attendeed was deleted from Talk.
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /attendees:
    get:
      summary: Retrieve an Attendee by Email or ID
      tags:
        - attendees
      operationId: getAttendeeByField
      parameters:
        - name: email
          in: query
          description: Attendee Email
          type: string
          format: email
        - name: id
          in: query
          description: Attendee ID
          type: string
      responses:
        200:
          description: find an attendee by id
          schema:
            $ref: "#/definitions/Attendee"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

    post:
      summary: Create an Attendee
      tags:
        - attendees
      consumes:
        - application/json
      parameters:
        - in: body
          name: attendee
          description: the Attendee to create
          schema:
            $ref: "#/definitions/Attendee"
      responses:
        200:
          description: Attendee was created
          schema:
            $ref: "#/definitions/Attendee"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /attendees/{id}:
    delete:
      summary: Deletes an Attendee by ID
      tags:
        - attendees
      operationId: deleteAttendeeById
      parameters:
        - name: id
          in: path
          description: Attendee ID
          type: string
          required: true
      responses:
        204:
          description: Attendee was deleted.
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

  /status:
    get:
      summary: Retrieve the System Status
      tags:
        - system
      responses:
        200:
          description: API is operating normally
          schema:
            type: object
            $ref: "#/definitions/SystemStatus"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"

definitions:

  Talk:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      refId:
        type: string
        readOnly: true
      refPath:
        type: string
        readOnly: true
      name:
        type: string
        minLength: 1
      presenter:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      date_time_start:
        type: string
        format: date-time
      date_time_end:
        type: string
        format: date-time
      ref_attendees:
        $ref: "#/definitions/AttendeeList"

  TalkList:
    type: array
    items:
      $ref: "#/definitions/Talk"

  Attendee:
    type: object
    required:
      - name_first
      - name_last
    properties:
      id:
        type: string
        readOnly: true
      refId:
        type: string
        readOnly: true
      refPath:
        type: string
        readOnly: true
      name_display:
        type: string
        minLength: 1
      name_first:
        type: string
        minLength: 1
      name_last:
        type: string
        minLength: 1
      email:
        type: string
        format: email
      ref_talks:
        $ref: "#/definitions/TalkList"

  AttendeeList:
    type: array
    items:
      $ref: "#/definitions/Attendee"

  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

  SystemStatus:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
