---
swagger: "2.0"
info:
  description: A simple talk attendance API
  title: attend.io
  version: 1.0.0
consumes:
- application/github.com/sctskw/attend.io.v1+json
produces:
  - application/github.com/sctskw/attend.io.v1+json
schemes:
  - http
paths:
  /:
    get:
      tags:
        - status
      responses:
        200:
          description: api status
          schema:
            type: object
            $ref: "#/definitions/status"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /talks:
    get:
      tags:
        - talks
      responses:
        200:
          description: list the talks
          schema:
            type: array
            items:
              $ref: "#/definitions/talk"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"

definitions:
  talk:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
  attendee:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: uuid
        readOnly: true
      name:
        type: string
        minLength: 1
  event:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: uuid
        readOnly: true
      name:
        type: string
        minLength: 1
      talk:
        type: integer
        format: uuid
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  status:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
