// Code generated by go-swagger; DO NOT EDIT.

package attendees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAttendeeHandlerFunc turns a function with the right signature into a delete attendee handler
type DeleteAttendeeHandlerFunc func(DeleteAttendeeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAttendeeHandlerFunc) Handle(params DeleteAttendeeParams) middleware.Responder {
	return fn(params)
}

// DeleteAttendeeHandler interface for that can handle valid delete attendee params
type DeleteAttendeeHandler interface {
	Handle(DeleteAttendeeParams) middleware.Responder
}

// NewDeleteAttendee creates a new http.Handler for the delete attendee operation
func NewDeleteAttendee(ctx *middleware.Context, handler DeleteAttendeeHandler) *DeleteAttendee {
	return &DeleteAttendee{Context: ctx, Handler: handler}
}

/*DeleteAttendee swagger:route DELETE /attendees/{id} attendees deleteAttendee

Deletes an Attendee with specific ID

*/
type DeleteAttendee struct {
	Context *middleware.Context
	Handler DeleteAttendeeHandler
}

func (o *DeleteAttendee) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteAttendeeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
