// Code generated by go-swagger; DO NOT EDIT.

package attendees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAttendeesByHandlerFunc turns a function with the right signature into a get attendees by handler
type GetAttendeesByHandlerFunc func(GetAttendeesByParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAttendeesByHandlerFunc) Handle(params GetAttendeesByParams) middleware.Responder {
	return fn(params)
}

// GetAttendeesByHandler interface for that can handle valid get attendees by params
type GetAttendeesByHandler interface {
	Handle(GetAttendeesByParams) middleware.Responder
}

// NewGetAttendeesBy creates a new http.Handler for the get attendees by operation
func NewGetAttendeesBy(ctx *middleware.Context, handler GetAttendeesByHandler) *GetAttendeesBy {
	return &GetAttendeesBy{Context: ctx, Handler: handler}
}

/*GetAttendeesBy swagger:route GET /attendee attendees getAttendeesBy

GetAttendeesBy get attendees by API

*/
type GetAttendeesBy struct {
	Context *middleware.Context
	Handler GetAttendeesByHandler
}

func (o *GetAttendeesBy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAttendeesByParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
