// Code generated by go-swagger; DO NOT EDIT.

package attendees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetAttendeesByEventIDParams creates a new GetAttendeesByEventIDParams object
// no default values defined in spec.
func NewGetAttendeesByEventIDParams() GetAttendeesByEventIDParams {

	return GetAttendeesByEventIDParams{}
}

// GetAttendeesByEventIDParams contains all the bound params for the get attendees by event Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAttendeesByEventId
type GetAttendeesByEventIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Event ID
	  Required: true
	  In: path
	*/
	EventID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAttendeesByEventIDParams() beforehand.
func (o *GetAttendeesByEventIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rEventID, rhkEventID, _ := route.Params.GetOK("eventId")
	if err := o.bindEventID(rEventID, rhkEventID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEventID binds and validates parameter EventID from path.
func (o *GetAttendeesByEventIDParams) bindEventID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("eventId", "path", "strfmt.UUID", raw)
	}
	o.EventID = *(value.(*strfmt.UUID))

	if err := o.validateEventID(formats); err != nil {
		return err
	}

	return nil
}

// validateEventID carries on validations for parameter EventID
func (o *GetAttendeesByEventIDParams) validateEventID(formats strfmt.Registry) error {

	if err := validate.FormatOf("eventId", "path", "uuid", o.EventID.String(), formats); err != nil {
		return err
	}
	return nil
}
