// Code generated by go-swagger; DO NOT EDIT.

package attendees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/sctskw/attend.io/models"
)

// NewPostAttendeesParams creates a new PostAttendeesParams object
// no default values defined in spec.
func NewPostAttendeesParams() PostAttendeesParams {

	return PostAttendeesParams{}
}

// PostAttendeesParams contains all the bound params for the post attendees operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostAttendees
type PostAttendeesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the Attendee to create
	  In: body
	*/
	Attendee *models.Attendee
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAttendeesParams() beforehand.
func (o *PostAttendeesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Attendee
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("attendee", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Attendee = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
