// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteTalksIDHandlerFunc turns a function with the right signature into a delete talks ID handler
type DeleteTalksIDHandlerFunc func(DeleteTalksIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTalksIDHandlerFunc) Handle(params DeleteTalksIDParams) middleware.Responder {
	return fn(params)
}

// DeleteTalksIDHandler interface for that can handle valid delete talks ID params
type DeleteTalksIDHandler interface {
	Handle(DeleteTalksIDParams) middleware.Responder
}

// NewDeleteTalksID creates a new http.Handler for the delete talks ID operation
func NewDeleteTalksID(ctx *middleware.Context, handler DeleteTalksIDHandler) *DeleteTalksID {
	return &DeleteTalksID{Context: ctx, Handler: handler}
}

/*DeleteTalksID swagger:route DELETE /talks/{id} deleteTalksId

Deletes a Talk with specific ID

*/
type DeleteTalksID struct {
	Context *middleware.Context
	Handler DeleteTalksIDHandler
}

func (o *DeleteTalksID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTalksIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
