// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTalksIDNoContentCode is the HTTP code returned for type DeleteTalksIDNoContent
const DeleteTalksIDNoContentCode int = 204

/*DeleteTalksIDNoContent Talk was deleted.

swagger:response deleteTalksIdNoContent
*/
type DeleteTalksIDNoContent struct {
}

// NewDeleteTalksIDNoContent creates DeleteTalksIDNoContent with default headers values
func NewDeleteTalksIDNoContent() *DeleteTalksIDNoContent {

	return &DeleteTalksIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteTalksIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
