// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventAttendeesHandlerFunc turns a function with the right signature into a get event attendees handler
type GetEventAttendeesHandlerFunc func(GetEventAttendeesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventAttendeesHandlerFunc) Handle(params GetEventAttendeesParams) middleware.Responder {
	return fn(params)
}

// GetEventAttendeesHandler interface for that can handle valid get event attendees params
type GetEventAttendeesHandler interface {
	Handle(GetEventAttendeesParams) middleware.Responder
}

// NewGetEventAttendees creates a new http.Handler for the get event attendees operation
func NewGetEventAttendees(ctx *middleware.Context, handler GetEventAttendeesHandler) *GetEventAttendees {
	return &GetEventAttendees{Context: ctx, Handler: handler}
}

/*GetEventAttendees swagger:route GET /events/{id}/attendees events getEventAttendees

GetEventAttendees get event attendees API

*/
type GetEventAttendees struct {
	Context *middleware.Context
	Handler GetEventAttendeesHandler
}

func (o *GetEventAttendees) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEventAttendeesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
