// Code generated by go-swagger; DO NOT EDIT.

// Package restapi attend.io
//
//  A simple talk attendance API
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/github.com/sctskw/attend.io.v1+json
//    - application/json
//
//  Produces:
//    - application/github.com/sctskw/attend.io.v1+json
//
// swagger:meta
package restapi
