// Code generated by go-swagger; DO NOT EDIT.

package talks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddAttendeeToTalkHandlerFunc turns a function with the right signature into a add attendee to talk handler
type AddAttendeeToTalkHandlerFunc func(AddAttendeeToTalkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddAttendeeToTalkHandlerFunc) Handle(params AddAttendeeToTalkParams) middleware.Responder {
	return fn(params)
}

// AddAttendeeToTalkHandler interface for that can handle valid add attendee to talk params
type AddAttendeeToTalkHandler interface {
	Handle(AddAttendeeToTalkParams) middleware.Responder
}

// NewAddAttendeeToTalk creates a new http.Handler for the add attendee to talk operation
func NewAddAttendeeToTalk(ctx *middleware.Context, handler AddAttendeeToTalkHandler) *AddAttendeeToTalk {
	return &AddAttendeeToTalk{Context: ctx, Handler: handler}
}

/*AddAttendeeToTalk swagger:route PATCH /talks/{id}/attendees talks addAttendeeToTalk

Add an Attendee to a Talk

*/
type AddAttendeeToTalk struct {
	Context *middleware.Context
	Handler AddAttendeeToTalkHandler
}

func (o *AddAttendeeToTalk) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddAttendeeToTalkParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
