// Code generated by go-swagger; DO NOT EDIT.

package talks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteTalkByIDHandlerFunc turns a function with the right signature into a delete talk by Id handler
type DeleteTalkByIDHandlerFunc func(DeleteTalkByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTalkByIDHandlerFunc) Handle(params DeleteTalkByIDParams) middleware.Responder {
	return fn(params)
}

// DeleteTalkByIDHandler interface for that can handle valid delete talk by Id params
type DeleteTalkByIDHandler interface {
	Handle(DeleteTalkByIDParams) middleware.Responder
}

// NewDeleteTalkByID creates a new http.Handler for the delete talk by Id operation
func NewDeleteTalkByID(ctx *middleware.Context, handler DeleteTalkByIDHandler) *DeleteTalkByID {
	return &DeleteTalkByID{Context: ctx, Handler: handler}
}

/*DeleteTalkByID swagger:route DELETE /talks/{id} talks deleteTalkById

Deletes a Talk with specific ID

*/
type DeleteTalkByID struct {
	Context *middleware.Context
	Handler DeleteTalkByIDHandler
}

func (o *DeleteTalkByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTalkByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
