// Code generated by go-swagger; DO NOT EDIT.

package talks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTalksHandlerFunc turns a function with the right signature into a get talks handler
type GetTalksHandlerFunc func(GetTalksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTalksHandlerFunc) Handle(params GetTalksParams) middleware.Responder {
	return fn(params)
}

// GetTalksHandler interface for that can handle valid get talks params
type GetTalksHandler interface {
	Handle(GetTalksParams) middleware.Responder
}

// NewGetTalks creates a new http.Handler for the get talks operation
func NewGetTalks(ctx *middleware.Context, handler GetTalksHandler) *GetTalks {
	return &GetTalks{Context: ctx, Handler: handler}
}

/*GetTalks swagger:route GET /talks talks getTalks

retrieve all Talks

*/
type GetTalks struct {
	Context *middleware.Context
	Handler GetTalksHandler
}

func (o *GetTalks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTalksParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
