// Code generated by go-swagger; DO NOT EDIT.

package talks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sctskw/attend.io/models"
)

// GetTalkByIDOKCode is the HTTP code returned for type GetTalkByIDOK
const GetTalkByIDOKCode int = 200

/*GetTalkByIDOK the requested talk

swagger:response getTalkByIdOK
*/
type GetTalkByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Talk `json:"body,omitempty"`
}

// NewGetTalkByIDOK creates GetTalkByIDOK with default headers values
func NewGetTalkByIDOK() *GetTalkByIDOK {

	return &GetTalkByIDOK{}
}

// WithPayload adds the payload to the get talk by Id o k response
func (o *GetTalkByIDOK) WithPayload(payload *models.Talk) *GetTalkByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get talk by Id o k response
func (o *GetTalkByIDOK) SetPayload(payload *models.Talk) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTalkByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTalkByIDDefault generic error response

swagger:response getTalkByIdDefault
*/
type GetTalkByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTalkByIDDefault creates GetTalkByIDDefault with default headers values
func NewGetTalkByIDDefault(code int) *GetTalkByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTalkByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get talk by Id default response
func (o *GetTalkByIDDefault) WithStatusCode(code int) *GetTalkByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get talk by Id default response
func (o *GetTalkByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get talk by Id default response
func (o *GetTalkByIDDefault) WithPayload(payload *models.Error) *GetTalkByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get talk by Id default response
func (o *GetTalkByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTalkByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
