// Code generated by go-swagger; DO NOT EDIT.

package talks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/sctskw/attend.io/models"
)

// NewPostTalksParams creates a new PostTalksParams object
// no default values defined in spec.
func NewPostTalksParams() PostTalksParams {

	return PostTalksParams{}
}

// PostTalksParams contains all the bound params for the post talks operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostTalks
type PostTalksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the Talk to create
	  In: body
	*/
	Talk *models.Talk
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostTalksParams() beforehand.
func (o *PostTalksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Talk
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("talk", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Talk = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
