// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Event event
//
// swagger:model Event
type Event struct {

	// date time end
	// Format: date-time
	DateTimeEnd strfmt.DateTime `json:"date_time_end,omitempty"`

	// date time start
	// Format: date-time
	DateTimeStart strfmt.DateTime `json:"date_time_start,omitempty"`

	// id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// name
	// Required: true
	// Min Length: 1
	Name *string `json:"name"`

	// ref attendees
	RefAttendees AttendeesList `json:"ref_attendees,omitempty"`

	// ref talk
	RefTalk *Talk `json:"ref_talk,omitempty"`
}

// Validate validates this event
func (m *Event) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateTimeEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateTimeStart(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefAttendees(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefTalk(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Event) validateDateTimeEnd(formats strfmt.Registry) error {

	if swag.IsZero(m.DateTimeEnd) { // not required
		return nil
	}

	if err := validate.FormatOf("date_time_end", "body", "date-time", m.DateTimeEnd.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Event) validateDateTimeStart(formats strfmt.Registry) error {

	if swag.IsZero(m.DateTimeStart) { // not required
		return nil
	}

	if err := validate.FormatOf("date_time_start", "body", "date-time", m.DateTimeStart.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Event) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", string(*m.Name), 1); err != nil {
		return err
	}

	return nil
}

func (m *Event) validateRefAttendees(formats strfmt.Registry) error {

	if swag.IsZero(m.RefAttendees) { // not required
		return nil
	}

	if err := m.RefAttendees.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("ref_attendees")
		}
		return err
	}

	return nil
}

func (m *Event) validateRefTalk(formats strfmt.Registry) error {

	if swag.IsZero(m.RefTalk) { // not required
		return nil
	}

	if m.RefTalk != nil {
		if err := m.RefTalk.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ref_talk")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Event) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Event) UnmarshalBinary(b []byte) error {
	var res Event
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
